# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='poked_by', to='pokes_app.User'),
        ),
    ]
