# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes_app', '0002_auto_20171027_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='poked_users',
        ),
        migrations.AddField(
            model_name='poke',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_pokes', to='pokes_app.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pokes', to='pokes_app.User'),
        ),
    ]
