# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes_app', '0003_auto_20171027_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='receiver',
        ),
        migrations.AddField(
            model_name='poke',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='pokes_app.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='poke_history',
            field=models.IntegerField(default=0),
        ),
    ]
