# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes_app', '0004_auto_20171027_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='pokes_app.User'),
        ),
    ]
